<script type="text/javascript" src="_js/jquery-3.1.1.min.js"></script>
<!-- http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js -->
<script type="text/javascript" src="_js/bootstrap.min.js"></script>
<!-- https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js -->
<script type="text/javascript" src="_js/jasny-bootstrap.min.js"></script>
<script type="text/javascript" src="_js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="_js/jquery-ui.min.js"></script>
<script type="text/javascript" src="_js/jquery-ui-jalali.min.js"></script>
<script type="text/javascript" src="_js/script.js"></script>
